MVCProject/Controllers/LoginController.cs
using DapperDataAccessLayer;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace MVCProject.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View("LoginForm",new LoginModel());
        }
        /*public ActionResult Create(Registration value)
        {
            var model = _Registers.Security(value);
            if (model == true)
            {
                var ans = _Registers.GetAllRegistration(value);
                return View("Create", ans);
            }

            *//* var model = new Registration();
             return View("Create",model);*//*
        }
*/


        /*public ActionResult Login(LoginModel log)
        {
            // Assuming you have a method to authenticate users in your data access layer
            bool isValid = DapperDataAccessLayer.ValidateUser(log.EmailID, log.Password);
            if (isValid)
            {
                // Authentication successful, perform necessary actions (e.g., set authentication cookie)
                return RedirectToAction("/Home/Index"); // Redirect to a dashboard or home page
            }
            else
            {
                ModelState.AddModelError("", "Invalid username or password");
                return View("LoginForm",log); // Return to the login page with an error message
            }
        }*/
        /* [HttpPost]
         public IActionResult Login(LoginModel log)
         {
             return Redirect("/Home/IndeX");

         }*/
    }
}

MVCProject/Controllers/TicketRegistrationController.cs
using EntityFramework;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using DapperDataAccessLayer;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;


namespace MVCProject.Controllers
{
    public class TicketRegistrationController : Controller
    {
        private readonly ITicketRegistration _Register;
        private readonly string _connectionstring;
        public TicketRegistrationController(ITicketRegistration reg, IConfiguration configuration)
        {
            _Register = reg;
            _connectionstring = configuration.GetConnectionString("DbConnection");
        }
        // GET: RegistrationController
        public ActionResult Index()
        {
            var Results = _Register.GetAllRegistration();
            return View("List",Results);
        }
        public ActionResult Register()
        {
            return View("Create");
        }
        // GET: RegistrationController/Create
        public ActionResult Create(Registration value)
        {
            var model = _Register.Security(value);
            if (model == true)
            {
                var ans = _Register.GetAllRegistration();
                return View("List", ans);
            }
            else
            {
                return Redirect("/Login/Login");
            }

           /* var model = new Registration();
            return View("Create",model);*/
        }

        // POST: RegistrationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Creates( Registration detail)
        {
            var model = _Register.Login(detail);
            try
            {
                if(model==true)
                {
                    _Register.Insert(detail);
                    return Redirect("/Login/Login");
                }
                else
                {
                    
                    return View( "Create");
                }
               
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Details(long id)
        {
            var tkt =_Register.ReadbyID(id);
            return View("Details", tkt);
        }
        public ActionResult Edit(long id)
        {
            var tkt = _Register.ReadbyID(id);
            return View("Edit", tkt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(long id, Registration value)
        {
            _Register.Update (id,value);
            var ans = _Register.GetAllRegistration();
            return View("List", ans);
        }


        public ActionResult Home()
        {

           return Redirect("/Home/Index");
        }
        public ActionResult Delete(long id)
        {
            var tkt = _Register.ReadbyID(id);
            return View("Delete", tkt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Deletebyid(long RegistrationId)
        {
            _Register.Delete (RegistrationId);
            var ans = _Register.GetAllRegistration();
            return View("List",ans);
        }
    }
}

MVCProject/Views/TicketRegistration/Create.cshtml
@model EntityFramework.Registration

@{
    ViewData["Title"] = "Create";
    Layout = null;

}

<h1>Registration</h1>

<h4>Register and njoy</h4>
<hr />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<style>
    .container {
        
        margin: 100px;
    }

    /* Apply margin to form fields */
    input {
        margin-bottom: 50px;
    }

    /* Apply margin to buttons */
    button {
        margin-left:150px;
        margin-top: 10px;
    }
</style>
<div class=" container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Emailid" class="control-label"></label>
                            <input asp-for="Emailid" class="form-control" />

                            <span asp-validation-for="Emailid" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Password" class="control-label"></label>
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>

                        <div class="card-subtitle"> <button class="btn btn-outline-success" asp-controller="TicketRegistration" asp-action="Creates">Submit</button></div>
                        @*<input type="submit" value="Submit" class="btn btn-primary" />*@

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<div>
    <a asp-controller="Login" asp-action="Login">Back to Login</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCProject/Views/TicketRegistration/Delete.cshtml
@model EntityFramework.Registration

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Registration</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emailid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emailid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Deletebyid">
        <input type="hidden" asp-for="RegistrationId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCProject/Views/TicketRegistration/Details.cshtml
@model EntityFramework.Registration

@{
    ViewData["Title"] = "Details";
}

<h1> Register Details</h1>

<div>
    <h4>Registration</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emailid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emailid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RegistrationId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCProject/Views/TicketRegistration/Edit.cshtml
@model EntityFramework.Registration

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Registration</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RegistrationId" />
            <div class="form-group">
                <label asp-for="Emailid" class="control-label"></label>
                <input asp-for="Emailid" class="form-control" />
                <span asp-validation-for="Emailid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCProject/Views/TicketRegistration/List.cshtml
@model IEnumerable<EntityFramework.Registration>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Register</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Emailid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Emailid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.RegistrationId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.RegistrationId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.RegistrationId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>