MVCProject/Controllers/TicketBookingController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DapperDataAccessLayer;
using Microsoft.Extensions.Configuration;

namespace MVCProject.Controllers
{
    public class TicketBookingController : Controller
    {
        private readonly ITicketBooking _Result;
        private readonly ITicketLocations _loc;
        private readonly string _connectionstring;

        public TicketBookingController(ITicketBooking Results,ITicketLocations location, IConfiguration configuration)
        {
            _Result =Results;
            _loc = location;
            _connectionstring = configuration.GetConnectionString("DbConnection");
        }
        public ActionResult Index()
        {
            var ticket = _Result.ReadSP();
            return View("View" , ticket);
        }

        // GET: TicketBookingController1/Details/5
        public ActionResult Details(int id)
        {
            var tkt = _Result.ReadbyIDSP(id);
            tkt.Locations = _loc.GetAllLocations();
            return View("Details",tkt);
        }

        // GET: TicketBookingController1/Create
        public ActionResult Create()
        {
            var final = new TicketModel();
            final.Locations = _loc.GetAllLocations();
            return View("AddDetails", final);
        }

        // POST: TicketBookingController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(TicketModel final)
        {
            try
            {
                _Result.InsertSP(final);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TicketBookingController1/Edit/5
        public ActionResult Edit(int id)
        {
            var tkt = _Result.ReadbyIDSP(id);
            tkt.Locations = _loc.GetAllLocations();
            return View("Edit",tkt);
        }

        // POST: TicketBookingController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,TicketModel tkt)
        {
            try
            {
                _Result.UpdateSP(id, tkt);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TicketBookingController1/Delete/5
        public ActionResult Delete(int id)
        {
            var tkt = _Result.ReadbyIDSP(id);
            return View("Delete",tkt);
        }

        // POST: TicketBookingController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, TicketModel tkt)
        {
            try
            {
                _Result.DeleteSP(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCProject/Controllers/TicketRegistrationController.cs
using EntityFramework;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using DapperDataAccessLayer;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;


namespace MVCProject.Controllers
{
    public class TicketRegistrationController : Controller
    {
        private readonly ITicketRegistration _Register;
        private readonly string _connectionstring;
        public TicketRegistrationController(ITicketRegistration reg, IConfiguration configuration)
        {
            _Register = reg;
            _connectionstring = configuration.GetConnectionString("DbConnection");
        }
        // GET: RegistrationController
        public ActionResult Index()
        {
            var Results = _Register.GetAllRegistration();
            return View("List",Results);
        }
        public ActionResult Register()
        {
            return View("Create");
        }
        // GET: RegistrationController/Create
        public ActionResult Create(Registration value)
        {
            var model = _Register.Security(value);
            if (model == true)
            {
                var ans = _Register.GetAllRegistration();
                return View("List", ans);
            }
            else
            {
                return Redirect("/Login/Login");
            }

           /* var model = new Registration();
            return View("Create",model);*/
        }

        // POST: RegistrationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Creates( Registration detail)
        {
            var model = _Register.Login(detail);
            try
            {
                if(model==true)
                {
                    _Register.Insert(detail);
                    return Redirect("/Login/Login");
                }
                else
                {
                    
                    return View( "Create");
                }
               
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Details(long id)
        {
            var tkt =_Register.ReadbyID(id);
            return View("Details", tkt);
        }
        public ActionResult Edit(long id)
        {
            var tkt = _Register.ReadbyID(id);
            return View("Edit", tkt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(long id, Registration value)
        {
            _Register.Update (id,value);
            var ans = _Register.GetAllRegistration();
            return View("List", ans);
        }


        public ActionResult Home()
        {

           return Redirect("/Home/Index");
        }
        public ActionResult Delete(long id)
        {
            var tkt = _Register.ReadbyID(id);
            return View("Delete", tkt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Deletebyid(long RegistrationId)
        {
            _Register.Delete (RegistrationId);
            var ans = _Register.GetAllRegistration();
            return View("List",ans);
        }
    }
}

MVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ADTickets</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <nav class="navbar navbar-light bg-light">
                    <div class="container">
                        <a class="navbar-brand" href="#">
                            <img src="/images/tickets.jpg" alt="tickets" width="30" height="24"><b> ADTickets</b>
                        </a>
                    </div>
                </nav>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar nav-link text-dark ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TicketBooking" asp-action="Index">Ticket Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TicketRegistration" asp-action="Index">Registrations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
        <footer class="text-center bg-body-tertiary">
            <!-- Grid container -->
            <div class="container pt-4">
                <!-- Section: Social media -->
                <section class="mb-4">
                    <!-- Facebook -->
                    <a data-mdb-ripple-init
                       class="btn btn-link btn-floating btn-lg text-body m-1"
                       href=""
                       role="button"
                       data-mdb-ripple-color="dark">
                        <img src="/images/fab fa-facebook.png" alt="facebook" width="30" height="24">
                    </a>

                    <!-- Twitter -->
                    <a data-mdb-ripple-init
                       class="btn btn-link btn-floating btn-lg text-body m-1"
                       href="#!"
                       role="button"
                       data-mdb-ripple-color="dark">
                        <img src="/images/instagram-logo.png" alt="twitter" width="30" height="24">
                    </a>

                    <!-- Google -->
                    <a data-mdb-ripple-init
                       class="btn btn-link btn-floating btn-lg text-body m-1"
                       href="#!"
                       role="button"
                       data-mdb-ripple-color="dark">
                        <img src="/images/google-logo.png" alt="google" width="30" height="24">
                    </a>

                    <!-- Instagram -->
                    <a data-mdb-ripple-init
                       class="btn btn-link btn-floating btn-lg text-body m-1"
                       href="#!"
                       role="button"
                       data-mdb-ripple-color="dark">
                        <img src="/images/instagram-logo.png" alt="instagran" width="30" height="24">
                    </a>

                    <!-- Linkedin -->
                    <a data-mdb-ripple-init
                       class="btn btn-link btn-floating btn-lg text-body m-1"
                       href="#!"
                       role="button"
                       data-mdb-ripple-color="dark">
                        <img src="/images/linkedin-logo.png" alt="linkedin" width="30" height="24">
                    </a>
                    <!-- Github -->
                    <a data-mdb-ripple-init
                       class="btn btn-link btn-floating btn-lg text-body m-1"
                       href="#!"
                       role="button"
                       data-mdb-ripple-color="dark">
                        <img src="/images/githup-logo.png" alt="githup" width="30" height="24">
                    </a>
                </section>
                <!-- Section: Social media -->
            </div>
            <!-- Grid container -->
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05); font-size:smaller">
                <marquee direction="right">&copy;2024 ADTickets[India] All rights reserved</marquee>
              
            </div>
            <!-- Copyright -->
        </footer>
    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>